<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["wst_goods/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["wst_goods/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>GoodsId</th>
            <th>GoodsSn</th>
            <th>ProductNo</th>
            <th>GoodsName</th>
            <th>GoodsImg</th>
            <th>ShopId</th>
            <th>MarketPrice</th>
            <th>ShopPrice</th>
            <th>WarnStock</th>
            <th>GoodsStock</th>
            <th>GoodsUnit</th>
            <th>GoodsTips</th>
            <th>IsSale</th>
            <th>IsBest</th>
            <th>IsHot</th>
            <th>IsNew</th>
            <th>IsRecom</th>
            <th>GoodsCatIdPath</th>
            <th>GoodsCatId</th>
            <th>ShopCatId1</th>
            <th>ShopCatId2</th>
            <th>BrandId</th>
            <th>GoodsDesc</th>
            <th>GoodsStatus</th>
            <th>SaleNum</th>
            <th>SaleTime</th>
            <th>VisitNum</th>
            <th>AppraiseNum</th>
            <th>IsSpec</th>
            <th>Gallery</th>
            <th>GoodsSeoKeywords</th>
            <th>IllegalRemarks</th>
            <th>DataFlag</th>
            <th>CreateTime</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $wst_good): ?>
            <tr>
                <td><?php echo $wst_good->goodsId ?></td>
            <td><?php echo $wst_good->goodsSn ?></td>
            <td><?php echo $wst_good->productNo ?></td>
            <td><?php echo $wst_good->goodsName ?></td>
            <td><?php echo $wst_good->goodsImg ?></td>
            <td><?php echo $wst_good->shopId ?></td>
            <td><?php echo $wst_good->marketPrice ?></td>
            <td><?php echo $wst_good->shopPrice ?></td>
            <td><?php echo $wst_good->warnStock ?></td>
            <td><?php echo $wst_good->goodsStock ?></td>
            <td><?php echo $wst_good->goodsUnit ?></td>
            <td><?php echo $wst_good->goodsTips ?></td>
            <td><?php echo $wst_good->isSale ?></td>
            <td><?php echo $wst_good->isBest ?></td>
            <td><?php echo $wst_good->isHot ?></td>
            <td><?php echo $wst_good->isNew ?></td>
            <td><?php echo $wst_good->isRecom ?></td>
            <td><?php echo $wst_good->goodsCatIdPath ?></td>
            <td><?php echo $wst_good->goodsCatId ?></td>
            <td><?php echo $wst_good->shopCatId1 ?></td>
            <td><?php echo $wst_good->shopCatId2 ?></td>
            <td><?php echo $wst_good->brandId ?></td>
            <td><?php echo $wst_good->goodsDesc ?></td>
            <td><?php echo $wst_good->goodsStatus ?></td>
            <td><?php echo $wst_good->saleNum ?></td>
            <td><?php echo $wst_good->saleTime ?></td>
            <td><?php echo $wst_good->visitNum ?></td>
            <td><?php echo $wst_good->appraiseNum ?></td>
            <td><?php echo $wst_good->isSpec ?></td>
            <td><?php echo $wst_good->gallery ?></td>
            <td><?php echo $wst_good->goodsSeoKeywords ?></td>
            <td><?php echo $wst_good->illegalRemarks ?></td>
            <td><?php echo $wst_good->dataFlag ?></td>
            <td><?php echo $wst_good->createTime ?></td>

                <td><?php echo $this->tag->linkTo(["wst_goods/edit/" . $wst_good->goodsId, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["wst_goods/delete/" . $wst_good->goodsId, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("wst_goods/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("wst_goods/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("wst_goods/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("wst_goods/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
